// Generated by tools/gen-features.mjs.
import { readFile } from 'node:fs/promises';
const SLUGS = ["how-to-chat-with-your-documents-locally-offline-rag-no-cloud","connector-support-in-off-grid-ai-desktop-private-approval-gated-integrations","how-to-expose-on-device-ai-models-as-mcp-tools-local-mcp-server-no-cloud","how-to-export-ai-generated-web-pages-diagrams-and-code-in-off-grid-ai-in-2026"];
export default async () => ({ articles: (await Promise.all(SLUGS.map(async (s) => {
  try { const md = await readFile(`articles/${s}.md`, 'utf8'); const t = md.match(/^title:\s*"?(.*?)"?\s*$/m); return t ? { href: `/articles/${s}/`, title: t[1].replace(/\\"/g, '"') } : null; } catch { return null; }
}))).filter(Boolean) });
