// Generated by tools/gen-features.mjs.
import { readFile } from 'node:fs/promises';
const SLUGS = ["how-to-get-automatic-zoom-meeting-notes-on-your-mac-in-2026-no-cloud-transcription","how-to-find-something-you-saw-on-your-mac-in-2026-without-taking-notes","how-to-create-a-private-work-journal-from-your-mac-activity-in-2026-no-manual-logging","how-to-spot-focus-and-context-switching-patterns-in-your-mac-workday-in-2026"];
export default async () => ({ articles: (await Promise.all(SLUGS.map(async (s) => {
  try { const md = await readFile(`articles/${s}.md`, 'utf8'); const t = md.match(/^title:\s*"?(.*?)"?\s*$/m); return t ? { href: `/articles/${s}/`, title: t[1].replace(/\\"/g, '"') } : null; } catch { return null; }
}))).filter(Boolean) });
