// Generated by tools/gen-features.mjs. Edit preview-ui/pages/_features.mjs instead.
import React from 'react';
import FeaturePage from './_feature.jsx';
export default function Page({ data }) { return <FeaturePage slug="meetings-and-memory" data={data} />; }
