// Generated by tools/gen-features.mjs.
import { readFile } from 'node:fs/promises';
const SLUGS = ["do-you-need-a-powerful-computer-to-run-local-ai-in-2026","how-to-switch-between-local-and-remote-llms-on-your-phone-without-two-apps-or-two-workflows","how-to-explain-a-chart-with-local-ai-in-2026-without-uploading-the-image","how-to-run-a-local-openai-compatible-api-on-your-desktop-in-2026-no-cloud-no-keys"];
export default async () => ({ articles: (await Promise.all(SLUGS.map(async (s) => {
  try { const md = await readFile(`articles/${s}.md`, 'utf8'); const t = md.match(/^title:\s*"?(.*?)"?\s*$/m); return t ? { href: `/articles/${s}/`, title: t[1].replace(/\\"/g, '"') } : null; } catch { return null; }
}))).filter(Boolean) });
