// Generated by tools/gen-features.mjs.
import { readFile } from 'node:fs/promises';
const SLUGS = ["how-to-get-an-automatic-morning-briefing-of-meetings-and-to-dos-in-off-grid-ai-on-mac-in-2026","how-to-automate-tasks-in-your-signed-in-browser-with-local-ai-in-2026","how-to-dictate-into-any-mac-app-with-local-ai-in-2026-no-cloud-transcription","how-to-ask-ai-about-your-company-documents-in-2026-without-uploading-them"];
export default async () => ({ articles: (await Promise.all(SLUGS.map(async (s) => {
  try { const md = await readFile(`articles/${s}.md`, 'utf8'); const t = md.match(/^title:\s*"?(.*?)"?\s*$/m); return t ? { href: `/articles/${s}/`, title: t[1].replace(/\\"/g, '"') } : null; } catch { return null; }
}))).filter(Boolean) });
