// Generated by tools/gen-features.mjs.
import { readFile } from 'node:fs/promises';
const SLUGS = ["how-to-pair-your-phone-and-computer-in-off-grid-ai-in-2026-local-chat-and-file-sync","how-to-recover-text-you-copied-earlier-on-your-mac-in-2026-automatic-clipboard-history","how-to-store-api-keys-securely-on-your-computer-in-2026-no-cloud-vault","how-to-transfer-ai-models-from-your-computer-to-your-phone-in-2026-without-downloading-them-again"];
export default async () => ({ articles: (await Promise.all(SLUGS.map(async (s) => {
  try { const md = await readFile(`articles/${s}.md`, 'utf8'); const t = md.match(/^title:\s*"?(.*?)"?\s*$/m); return t ? { href: `/articles/${s}/`, title: t[1].replace(/\\"/g, '"') } : null; } catch { return null; }
}))).filter(Boolean) });
